"""Augmentation for the fine-tune: label-preserving rewrites of TUNE asks, generated by the local
open model (local-27b), filtered against every held-out ask of both corpora.

    python3 scripts/laya/paraphrase.py --train DIR/train.jsonl --out scripts/laya/data/paraphrases.jsonl

Per train row: four paraphrases that keep the task and its difficulty, one terse version, one noisy
one (typos, run-ons) — the `difficulty` styles the corpus scores separately. Each candidate is
dropped if ANY filter says it is close to ANY held-out ask: character-and-word similarity (the
corpus's own dedupe rule), word 3-gram Jaccard, difflib ratio, or a shared distinctive 6-gram. The
drops and their reasons are written beside the output. Resumable by parent id.
"""
import argparse
import difflib
import json
import os
import re
import sys
import time
import urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, os.path.join(HERE, "..", "ab", "corpus"))
import validate_corpus  # noqa: E402

PROMPT = """Rewrite the user's request below WITHOUT changing what is being asked or how hard it is: the same task, the same inputs, the same expected answer, the same amount of work. Do not answer it.

Return exactly one JSON object and nothing else:
{"paraphrases": [four different natural rewordings], "terse": "the same request in as few words as possible", "noisy": "the same request with a couple of typos and casual phrasing"}

REQUEST:
"""


def _words(t):
    return re.findall(r"[a-z0-9]+", t.lower())


def _ngrams(t, n):
    w = _words(t)
    return {tuple(w[i:i + n]) for i in range(max(0, len(w) - n + 1))}


def _jac(a, b):
    return len(a & b) / len(a | b) if a | b else 0.0


FILTERS = {
    "similar": lambda cand, held: validate_corpus.similar(cand, held) >= validate_corpus.DUP,
    "word3": lambda cand, held: _jac(_ngrams(cand, 3), _ngrams(held, 3)) >= 0.5,
    "difflib": lambda cand, held: difflib.SequenceMatcher(None, cand.lower(), held.lower()).ratio() >= 0.8,
    "shared6": lambda cand, held: bool(_ngrams(cand, 6) & _ngrams(held, 6)),
}


def leaks(candidate, held):
    """(held id, filter name) of the first filter that fires, or None."""
    for hid, message in held.items():
        for name, f in FILTERS.items():
            if f(candidate, message):
                return hid, name
    return None


def parse(text):
    s, e = (text or "").find("{"), (text or "").rfind("}")
    if s < 0 or e <= s:
        return []
    try:
        body = json.loads(text[s:e + 1])
    except ValueError:
        return []
    out = [("paraphrase", p) for p in body.get("paraphrases", [])[:4] if isinstance(p, str) and p.strip()]
    for kind in ("terse", "noisy"):
        if isinstance(body.get(kind), str) and body[kind].strip():
            out.append((kind, body[kind]))
    return out


def ask(base_url, auth, model, request, timeout=120):
    body = {"model": model, "messages": [{"role": "user", "content": PROMPT + request}], "temperature": 0.7,
            "max_tokens": 900, "chat_template_kwargs": {"enable_thinking": False}}
    req = urllib.request.Request(base_url.rstrip("/") + "/chat/completions", data=json.dumps(body).encode(),
                                 headers={"content-type": "application/json", "authorization": auth})
    with urllib.request.urlopen(req, timeout=timeout) as r:
        return json.load(r)["choices"][0]["message"]["content"]


def main(argv=None):
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--train", required=True, help="build_dataset.py's train.jsonl (parents)")
    ap.add_argument("--out", required=True)
    ap.add_argument("--base-url", default="http://127.0.0.1:8003/v1")
    ap.add_argument("--model", default="qwen3.8-27b")
    ap.add_argument("--token-file", default=os.path.expanduser("~/.fleet/secrets/spark27b.token"))
    args = ap.parse_args(argv)
    sys.path.insert(0, os.path.join(HERE, "..", "ab"))
    import split_tools
    ab = os.path.join(HERE, "..", "ab", "corpus")
    held = {}
    for name, key, split in (("requests.jsonl", "message", "tier-240"), ("dss-requests.jsonl", "message", "tier-240"),
                             ("cells-pilot.jsonl", "prompt", "cells-pilot")):
        ids = set(split_tools.load(split)["held"])
        held |= {r["id"]: r[key] for r in validate_corpus.load(os.path.join(ab, name)) if r["id"] in ids}
    token = open(args.token_file).read().strip()
    auth = token if token.startswith("Bearer ") else f"Bearer {token}"
    parents = [json.loads(l) for l in open(args.train) if l.strip()]
    done = set()
    if os.path.exists(args.out):
        done = {json.loads(l)["parent_id"] for l in open(args.out) if l.strip()}
    report_path = os.path.splitext(args.out)[0] + ".dropped.jsonl"
    todo = [p for p in parents if p["id"] not in done]
    print(f"[para] {len(todo)} of {len(parents)} parents to rewrite; {len(held)} held-out asks guard the output", flush=True)
    for n, p in enumerate(todo, 1):
        request = json.loads(p["state"])["request"]
        try:
            variants = parse(ask(args.base_url, auth, args.model, request))
        except Exception as e:
            print(f"[para] {p['id']}: {type(e).__name__}: {e}", flush=True)
            continue
        kept = []
        for i, (kind, text) in enumerate(variants):
            hit = leaks(text, held)
            if hit:
                with open(report_path, "a") as f:
                    f.write(json.dumps({"parent_id": p["id"], "kind": kind, "message": text, "held": hit[0], "filter": hit[1]}) + "\n")
                continue
            kept.append({"id": f"{p['id']}~{kind[0]}{i}", "parent_id": p["id"], "kind": kind, "message": text, "at": time.strftime("%Y-%m-%d")})
        with open(args.out, "a") as f:
            f.write("".join(json.dumps(k, ensure_ascii=False) + "\n" for k in kept) or
                    json.dumps({"id": f"{p['id']}~none", "parent_id": p["id"], "kind": "none", "message": None}) + "\n")
        if n % 20 == 0 or n == len(todo):
            print(f"[para] {n}/{len(todo)}", flush=True)
    return 0


if __name__ == "__main__":
    sys.exit(main())
